### ISSUE TITLE
Pgreco

### ISSUE THREAD

**Issue by ClaudioTazza** [lucifero55/MonteCarloRuzzon#1]
Si lavora

**Comment by ClaudioTazza** [comment]
![image](https://cloud.githubusercontent.com/assets/16176113/22550854/6bfef7ec-e952-11e6-9543-e37e1ce6ce5a.png)

**Comment by ClaudioTazza** [comment]
Non ricordo il rapporto che mi permetteva di calcolarmi il Pgreco

**Comment by FabioZTessitore** [comment]
Non ricordare, ragiona

**Comment by ClaudioTazza** [comment]
Come vuole che gestisca i punti?
  - Vettori 
  - Variabili vaganti
  - struct?

**Comment by FabioZTessitore** [comment]
Non ti serve niente del genere. Devi calcolare la distanza di un punto dall'origine

**Comment by ClaudioTazza** [comment]
Cosa non va nel codice?

**Comment by FabioZTessitore** [comment]
La funzione della distanza. Ti serve una distanza da origine

Il 6 feb 2017 4:46 PM, "lucifero55" <notifications@github.com> ha scritto:

**Comment by ClaudioTazza** [comment]
come si fa con cmake ad aggiungere la libreria math.h?

**Comment by FabioZTessitore** [comment]
Google

Il 6 feb 2017 5:01 PM, "lucifero55" <notifications@github.com> ha scritto:

**Comment by ClaudioTazza** [comment]
Ci provo ma sembra diversamente semplice

**Comment by ClaudioTazza** [comment]
suggerimenti?

**Comment by FabioZTessitore** [comment]
Che ti serve?

Il 7 feb 2017 8:24 PM, "lucifero55" <notifications@github.com> ha scritto:

**Comment by ClaudioTazza** [comment]
escono valori molto diversi da quelli di un ipotetico Pgreco

**Comment by ClaudioTazza** [comment]
che si avvicinano allo 0

**Comment by FabioZTessitore** [comment]
Quali frecce conti?

Ps. Random_between estrae numeri interi

Il 7 feb 2017 8:34 PM, "lucifero55" <notifications@github.com> ha scritto:

**Comment by ClaudioTazza** [comment]
Me ne ero appena accorto

**Comment by ClaudioTazza** [comment]
Quando il numero e' molto alto mi da come output -0.000

**Comment by ClaudioTazza** [comment]
Come mai?

**Comment by FabioZTessitore** [comment]
Sarà quella formula di geometria inventata. Mah

Il 7 feb 2017 8:43 PM, "lucifero55" <notifications@github.com> ha scritto:

**Comment by ClaudioTazza** [comment]
riga 26 o riga 21?

**Comment by FabioZTessitore** [comment]
Indovina? Tutte e due

Il 7 feb 2017 8:47 PM, "lucifero55" <notifications@github.com> ha scritto:

**Comment by lucifero55** [comment]
La prima calcola la distanza tra in punto della Freccia e l'origine (0, 0)
Formula sqrt( (x2 - x1)^2 + (y2 - y1)^2)
  dato che uno dei punti e' 0, 0 viene omesso, quindi
  sqrt( (x2 - x1)^2 )

**Comment by FabioZTessitore** [comment]
Quel quindi è altamente farlocco

Il 7 feb 2017 8:54 PM, "lucifero55" <notifications@github.com> ha scritto:

**Comment by lucifero55** [comment]
Uscirebbe sqrt( (x2 - x1)^2 + (0 - 0)^2 )
Non fa alcuna differenza

**Comment by ClaudioTazza** [comment]
![image](https://cloud.githubusercontent.com/assets/16176113/22708935/611c3b08-ed78-11e6-877a-eedf468a8fa3.png)
Questa e' la spiegazione della seconda

**Comment by FabioZTessitore** [comment]
Beata ignoranza

Il 7 feb 2017 9:00 PM, "lucifero55" <notifications@github.com> ha scritto:

**Comment by ClaudioTazza** [comment]
Lei e' una persona cattiva se mi lascia annegare nella mia ignoranza

**Comment by FabioZTessitore** [comment]
Glu glu glu

Il 7 feb 2017 9:03 PM, "lucifero55" <notifications@github.com> ha scritto:

**Comment by ClaudioTazza** [comment]
Nella foto non si vede ma nella parte finale e' Pgreco = Fg/Ft * 4

**Comment by FabioZTessitore** [comment]
Matematica e informatica non sono proprio sovrapponibili

Il 7 feb 2017 9:05 PM, "lucifero55" <notifications@github.com> ha scritto:

**Comment by ClaudioTazza** [comment]
Com'e' possibile?

**Comment by ClaudioTazza** [comment]
Il risultato gira intorno a 2.8

**Comment by ClaudioTazza** [comment]
Il programma e' basato sui calcoli sulla lavagna.
Se sono sbagliati non puo' che non funzionare.

Ora la domanda e dove sono sbagliati i calcoli?

**Comment by FabioZTessitore** [comment]
Random_between e distanza.
Come devo dirtelo?

Il 7 feb 2017 9:34 PM, "lucifero55" <notifications@github.com> ha scritto:

**Comment by ClaudioTazza** [comment]
Credo di aver capito il problema con distanza

**Comment by FabioZTessitore** [comment]
Resta il problema di random_between

**Comment by FabioZTessitore** [comment]
- elimina la variabile `n`
- non chiedere all'utente quante volte vuole calcolare pi greco, metti 10
- memorizza i risultati in una lista
