### ISSUE TITLE
simulazione

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/MonteCarloRuzzon#2]
in attesa

**Comment by ClaudioTazza** [comment]
Mi ripete il nome di quella operazione?

**Comment by FabioZTessitore** [comment]
devi calcolare la varianza

**Comment by ClaudioTazza** [comment]
Spiegazioni piu' dettagliate del messaggio di errore?

**Comment by ClaudioTazza** [comment]
Va bene?

**Comment by FabioZTessitore** [comment]
Riga 36, è proprio stile C, vedi se puoi riscriverla in python

Nel calcolo manca il quadrato

**Comment by ClaudioTazza** [comment]
Non credo di aver capito dove il quadrato debba essere messo

**Comment by FabioZTessitore** [comment]
Quella differenza deve essere al quadrato. Poi ci vuole una radice alla fine

**Comment by ClaudioTazza** [comment]
Qualcosa cosi'?

**Comment by FabioZTessitore** [comment]
La radice va fatta alla fine

**Comment by ClaudioTazza** [comment]
Dopo la somma?

**Comment by FabioZTessitore** [comment]
Si
